Search.appendIndex(
    [
                {
            "fqsen": "\\splitbrain\\phpcli\\Base",
            "name": "Base",
            "summary": "Class\u0020CLIBase",
            "url": "classes/splitbrain-phpcli-Base.html"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\Base\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "constructor",
            "url": "classes/splitbrain-phpcli-Base.html#method___construct"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\Base\u003A\u003Asetup\u0028\u0029",
            "name": "setup",
            "summary": "Register\u0020options\u0020and\u0020arguments\u0020on\u0020the\u0020given\u0020\u0024options\u0020object",
            "url": "classes/splitbrain-phpcli-Base.html#method_setup"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\Base\u003A\u003Amain\u0028\u0029",
            "name": "main",
            "summary": "Your\u0020main\u0020program",
            "url": "classes/splitbrain-phpcli-Base.html#method_main"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\Base\u003A\u003Arun\u0028\u0029",
            "name": "run",
            "summary": "Execute\u0020the\u0020CLI\u0020program",
            "url": "classes/splitbrain-phpcli-Base.html#method_run"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\Base\u003A\u003AregisterDefaultOptions\u0028\u0029",
            "name": "registerDefaultOptions",
            "summary": "Add\u0020the\u0020default\u0020help,\u0020color\u0020and\u0020log\u0020options",
            "url": "classes/splitbrain-phpcli-Base.html#method_registerDefaultOptions"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\Base\u003A\u003AhandleDefaultOptions\u0028\u0029",
            "name": "handleDefaultOptions",
            "summary": "Handle\u0020the\u0020default\u0020options",
            "url": "classes/splitbrain-phpcli-Base.html#method_handleDefaultOptions"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\Base\u003A\u003AsetupLogging\u0028\u0029",
            "name": "setupLogging",
            "summary": "Handle\u0020the\u0020logging\u0020options",
            "url": "classes/splitbrain-phpcli-Base.html#method_setupLogging"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\Base\u003A\u003AparseOptions\u0028\u0029",
            "name": "parseOptions",
            "summary": "Wrapper\u0020around\u0020the\u0020option\u0020parsing",
            "url": "classes/splitbrain-phpcli-Base.html#method_parseOptions"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\Base\u003A\u003AcheckArguments\u0028\u0029",
            "name": "checkArguments",
            "summary": "Wrapper\u0020around\u0020the\u0020argument\u0020checking",
            "url": "classes/splitbrain-phpcli-Base.html#method_checkArguments"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\Base\u003A\u003Aexecute\u0028\u0029",
            "name": "execute",
            "summary": "Wrapper\u0020around\u0020main",
            "url": "classes/splitbrain-phpcli-Base.html#method_execute"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\Base\u003A\u003AsetLogLevel\u0028\u0029",
            "name": "setLogLevel",
            "summary": "Set\u0020the\u0020current\u0020log\u0020level",
            "url": "classes/splitbrain-phpcli-Base.html#method_setLogLevel"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\Base\u003A\u003AisLogLevelEnabled\u0028\u0029",
            "name": "isLogLevelEnabled",
            "summary": "Check\u0020if\u0020a\u0020message\u0020with\u0020the\u0020given\u0020level\u0020should\u0020be\u0020logged",
            "url": "classes/splitbrain-phpcli-Base.html#method_isLogLevelEnabled"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\Base\u003A\u003Afatal\u0028\u0029",
            "name": "fatal",
            "summary": "Exits\u0020the\u0020program\u0020on\u0020a\u0020fatal\u0020error",
            "url": "classes/splitbrain-phpcli-Base.html#method_fatal"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\Base\u003A\u003Asuccess\u0028\u0029",
            "name": "success",
            "summary": "Normal,\u0020positive\u0020outcome\u0020\u0028This\u0020is\u0020not\u0020a\u0020PSR\u002D3\u0020level\u0029",
            "url": "classes/splitbrain-phpcli-Base.html#method_success"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\Base\u003A\u003AlogMessage\u0028\u0029",
            "name": "logMessage",
            "summary": "",
            "url": "classes/splitbrain-phpcli-Base.html#method_logMessage"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\Base\u003A\u003Ainterpolate\u0028\u0029",
            "name": "interpolate",
            "summary": "Interpolates\u0020context\u0020values\u0020into\u0020the\u0020message\u0020placeholders.",
            "url": "classes/splitbrain-phpcli-Base.html#method_interpolate"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\Base\u003A\u003A\u0024bin",
            "name": "bin",
            "summary": "",
            "url": "classes/splitbrain-phpcli-Base.html#property_bin"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\Base\u003A\u003A\u0024options",
            "name": "options",
            "summary": "",
            "url": "classes/splitbrain-phpcli-Base.html#property_options"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\Base\u003A\u003A\u0024colors",
            "name": "colors",
            "summary": "",
            "url": "classes/splitbrain-phpcli-Base.html#property_colors"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\Base\u003A\u003A\u0024loglevel",
            "name": "loglevel",
            "summary": "",
            "url": "classes/splitbrain-phpcli-Base.html#property_loglevel"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\Base\u003A\u003A\u0024logdefault",
            "name": "logdefault",
            "summary": "",
            "url": "classes/splitbrain-phpcli-Base.html#property_logdefault"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\CLI",
            "name": "CLI",
            "summary": "Class\u0020CLI",
            "url": "classes/splitbrain-phpcli-CLI.html"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\CLI\u003A\u003Aemergency\u0028\u0029",
            "name": "emergency",
            "summary": "System\u0020is\u0020unusable.",
            "url": "classes/splitbrain-phpcli-CLI.html#method_emergency"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\CLI\u003A\u003Aalert\u0028\u0029",
            "name": "alert",
            "summary": "Action\u0020must\u0020be\u0020taken\u0020immediately.",
            "url": "classes/splitbrain-phpcli-CLI.html#method_alert"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\CLI\u003A\u003Acritical\u0028\u0029",
            "name": "critical",
            "summary": "Critical\u0020conditions.",
            "url": "classes/splitbrain-phpcli-CLI.html#method_critical"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\CLI\u003A\u003Aerror\u0028\u0029",
            "name": "error",
            "summary": "Runtime\u0020errors\u0020that\u0020do\u0020not\u0020require\u0020immediate\u0020action\u0020but\u0020should\u0020typically\nbe\u0020logged\u0020and\u0020monitored.",
            "url": "classes/splitbrain-phpcli-CLI.html#method_error"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\CLI\u003A\u003Awarning\u0028\u0029",
            "name": "warning",
            "summary": "Exceptional\u0020occurrences\u0020that\u0020are\u0020not\u0020errors.",
            "url": "classes/splitbrain-phpcli-CLI.html#method_warning"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\CLI\u003A\u003Anotice\u0028\u0029",
            "name": "notice",
            "summary": "Normal\u0020but\u0020significant\u0020events.",
            "url": "classes/splitbrain-phpcli-CLI.html#method_notice"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\CLI\u003A\u003Ainfo\u0028\u0029",
            "name": "info",
            "summary": "Interesting\u0020events.",
            "url": "classes/splitbrain-phpcli-CLI.html#method_info"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\CLI\u003A\u003Adebug\u0028\u0029",
            "name": "debug",
            "summary": "Detailed\u0020debug\u0020information.",
            "url": "classes/splitbrain-phpcli-CLI.html#method_debug"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\CLI\u003A\u003Alog\u0028\u0029",
            "name": "log",
            "summary": "",
            "url": "classes/splitbrain-phpcli-CLI.html#method_log"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\Colors",
            "name": "Colors",
            "summary": "Class\u0020Colors",
            "url": "classes/splitbrain-phpcli-Colors.html"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\Colors\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor",
            "url": "classes/splitbrain-phpcli-Colors.html#method___construct"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\Colors\u003A\u003Aenable\u0028\u0029",
            "name": "enable",
            "summary": "enable\u0020color\u0020output",
            "url": "classes/splitbrain-phpcli-Colors.html#method_enable"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\Colors\u003A\u003Adisable\u0028\u0029",
            "name": "disable",
            "summary": "disable\u0020color\u0020output",
            "url": "classes/splitbrain-phpcli-Colors.html#method_disable"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\Colors\u003A\u003AisEnabled\u0028\u0029",
            "name": "isEnabled",
            "summary": "",
            "url": "classes/splitbrain-phpcli-Colors.html#method_isEnabled"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\Colors\u003A\u003Aptln\u0028\u0029",
            "name": "ptln",
            "summary": "Convenience\u0020function\u0020to\u0020print\u0020a\u0020line\u0020in\u0020a\u0020given\u0020color",
            "url": "classes/splitbrain-phpcli-Colors.html#method_ptln"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\Colors\u003A\u003Awrap\u0028\u0029",
            "name": "wrap",
            "summary": "Returns\u0020the\u0020given\u0020text\u0020wrapped\u0020in\u0020the\u0020appropriate\u0020color\u0020and\u0020reset\u0020code",
            "url": "classes/splitbrain-phpcli-Colors.html#method_wrap"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\Colors\u003A\u003AgetColorCode\u0028\u0029",
            "name": "getColorCode",
            "summary": "Gets\u0020the\u0020appropriate\u0020terminal\u0020code\u0020for\u0020the\u0020given\u0020color",
            "url": "classes/splitbrain-phpcli-Colors.html#method_getColorCode"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\Colors\u003A\u003Aset\u0028\u0029",
            "name": "set",
            "summary": "Set\u0020the\u0020given\u0020color\u0020for\u0020consecutive\u0020output",
            "url": "classes/splitbrain-phpcli-Colors.html#method_set"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\Colors\u003A\u003Areset\u0028\u0029",
            "name": "reset",
            "summary": "reset\u0020the\u0020terminal\u0020color",
            "url": "classes/splitbrain-phpcli-Colors.html#method_reset"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\Colors\u003A\u003AC_RESET",
            "name": "C_RESET",
            "summary": "",
            "url": "classes/splitbrain-phpcli-Colors.html#constant_C_RESET"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\Colors\u003A\u003AC_BLACK",
            "name": "C_BLACK",
            "summary": "",
            "url": "classes/splitbrain-phpcli-Colors.html#constant_C_BLACK"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\Colors\u003A\u003AC_DARKGRAY",
            "name": "C_DARKGRAY",
            "summary": "",
            "url": "classes/splitbrain-phpcli-Colors.html#constant_C_DARKGRAY"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\Colors\u003A\u003AC_BLUE",
            "name": "C_BLUE",
            "summary": "",
            "url": "classes/splitbrain-phpcli-Colors.html#constant_C_BLUE"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\Colors\u003A\u003AC_LIGHTBLUE",
            "name": "C_LIGHTBLUE",
            "summary": "",
            "url": "classes/splitbrain-phpcli-Colors.html#constant_C_LIGHTBLUE"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\Colors\u003A\u003AC_GREEN",
            "name": "C_GREEN",
            "summary": "",
            "url": "classes/splitbrain-phpcli-Colors.html#constant_C_GREEN"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\Colors\u003A\u003AC_LIGHTGREEN",
            "name": "C_LIGHTGREEN",
            "summary": "",
            "url": "classes/splitbrain-phpcli-Colors.html#constant_C_LIGHTGREEN"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\Colors\u003A\u003AC_CYAN",
            "name": "C_CYAN",
            "summary": "",
            "url": "classes/splitbrain-phpcli-Colors.html#constant_C_CYAN"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\Colors\u003A\u003AC_LIGHTCYAN",
            "name": "C_LIGHTCYAN",
            "summary": "",
            "url": "classes/splitbrain-phpcli-Colors.html#constant_C_LIGHTCYAN"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\Colors\u003A\u003AC_RED",
            "name": "C_RED",
            "summary": "",
            "url": "classes/splitbrain-phpcli-Colors.html#constant_C_RED"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\Colors\u003A\u003AC_LIGHTRED",
            "name": "C_LIGHTRED",
            "summary": "",
            "url": "classes/splitbrain-phpcli-Colors.html#constant_C_LIGHTRED"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\Colors\u003A\u003AC_PURPLE",
            "name": "C_PURPLE",
            "summary": "",
            "url": "classes/splitbrain-phpcli-Colors.html#constant_C_PURPLE"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\Colors\u003A\u003AC_LIGHTPURPLE",
            "name": "C_LIGHTPURPLE",
            "summary": "",
            "url": "classes/splitbrain-phpcli-Colors.html#constant_C_LIGHTPURPLE"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\Colors\u003A\u003AC_BROWN",
            "name": "C_BROWN",
            "summary": "",
            "url": "classes/splitbrain-phpcli-Colors.html#constant_C_BROWN"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\Colors\u003A\u003AC_YELLOW",
            "name": "C_YELLOW",
            "summary": "",
            "url": "classes/splitbrain-phpcli-Colors.html#constant_C_YELLOW"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\Colors\u003A\u003AC_LIGHTGRAY",
            "name": "C_LIGHTGRAY",
            "summary": "",
            "url": "classes/splitbrain-phpcli-Colors.html#constant_C_LIGHTGRAY"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\Colors\u003A\u003AC_WHITE",
            "name": "C_WHITE",
            "summary": "",
            "url": "classes/splitbrain-phpcli-Colors.html#constant_C_WHITE"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\Colors\u003A\u003AC_CODE_REGEX",
            "name": "C_CODE_REGEX",
            "summary": "",
            "url": "classes/splitbrain-phpcli-Colors.html#constant_C_CODE_REGEX"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\Colors\u003A\u003A\u0024colors",
            "name": "colors",
            "summary": "",
            "url": "classes/splitbrain-phpcli-Colors.html#property_colors"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\Colors\u003A\u003A\u0024enabled",
            "name": "enabled",
            "summary": "",
            "url": "classes/splitbrain-phpcli-Colors.html#property_enabled"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\Exception",
            "name": "Exception",
            "summary": "Class\u0020Exception",
            "url": "classes/splitbrain-phpcli-Exception.html"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\Exception\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/splitbrain-phpcli-Exception.html#method___construct"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\Exception\u003A\u003AE_ANY",
            "name": "E_ANY",
            "summary": "",
            "url": "classes/splitbrain-phpcli-Exception.html#constant_E_ANY"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\Exception\u003A\u003AE_UNKNOWN_OPT",
            "name": "E_UNKNOWN_OPT",
            "summary": "",
            "url": "classes/splitbrain-phpcli-Exception.html#constant_E_UNKNOWN_OPT"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\Exception\u003A\u003AE_OPT_ARG_REQUIRED",
            "name": "E_OPT_ARG_REQUIRED",
            "summary": "",
            "url": "classes/splitbrain-phpcli-Exception.html#constant_E_OPT_ARG_REQUIRED"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\Exception\u003A\u003AE_OPT_ARG_DENIED",
            "name": "E_OPT_ARG_DENIED",
            "summary": "",
            "url": "classes/splitbrain-phpcli-Exception.html#constant_E_OPT_ARG_DENIED"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\Exception\u003A\u003AE_OPT_ABIGUOUS",
            "name": "E_OPT_ABIGUOUS",
            "summary": "",
            "url": "classes/splitbrain-phpcli-Exception.html#constant_E_OPT_ABIGUOUS"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\Exception\u003A\u003AE_ARG_READ",
            "name": "E_ARG_READ",
            "summary": "",
            "url": "classes/splitbrain-phpcli-Exception.html#constant_E_ARG_READ"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\Options",
            "name": "Options",
            "summary": "Class\u0020Options",
            "url": "classes/splitbrain-phpcli-Options.html"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\Options\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor",
            "url": "classes/splitbrain-phpcli-Options.html#method___construct"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\Options\u003A\u003AgetBin\u0028\u0029",
            "name": "getBin",
            "summary": "Gets\u0020the\u0020bin\u0020value",
            "url": "classes/splitbrain-phpcli-Options.html#method_getBin"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\Options\u003A\u003AsetHelp\u0028\u0029",
            "name": "setHelp",
            "summary": "Sets\u0020the\u0020help\u0020text\u0020for\u0020the\u0020tool\u0020itself",
            "url": "classes/splitbrain-phpcli-Options.html#method_setHelp"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\Options\u003A\u003AsetCommandHelp\u0028\u0029",
            "name": "setCommandHelp",
            "summary": "Sets\u0020the\u0020help\u0020text\u0020for\u0020the\u0020tools\u0020commands\u0020itself",
            "url": "classes/splitbrain-phpcli-Options.html#method_setCommandHelp"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\Options\u003A\u003AuseCompactHelp\u0028\u0029",
            "name": "useCompactHelp",
            "summary": "Use\u0020a\u0020more\u0020compact\u0020help\u0020screen\u0020with\u0020less\u0020new\u0020lines",
            "url": "classes/splitbrain-phpcli-Options.html#method_useCompactHelp"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\Options\u003A\u003AregisterArgument\u0028\u0029",
            "name": "registerArgument",
            "summary": "Register\u0020the\u0020names\u0020of\u0020arguments\u0020for\u0020help\u0020generation\u0020and\u0020number\u0020checking",
            "url": "classes/splitbrain-phpcli-Options.html#method_registerArgument"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\Options\u003A\u003AregisterCommand\u0028\u0029",
            "name": "registerCommand",
            "summary": "This\u0020registers\u0020a\u0020sub\u0020command",
            "url": "classes/splitbrain-phpcli-Options.html#method_registerCommand"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\Options\u003A\u003AregisterOption\u0028\u0029",
            "name": "registerOption",
            "summary": "Register\u0020an\u0020option\u0020for\u0020option\u0020parsing\u0020and\u0020help\u0020generation",
            "url": "classes/splitbrain-phpcli-Options.html#method_registerOption"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\Options\u003A\u003AcheckArguments\u0028\u0029",
            "name": "checkArguments",
            "summary": "Checks\u0020the\u0020actual\u0020number\u0020of\u0020arguments\u0020against\u0020the\u0020required\u0020number",
            "url": "classes/splitbrain-phpcli-Options.html#method_checkArguments"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\Options\u003A\u003AparseOptions\u0028\u0029",
            "name": "parseOptions",
            "summary": "Parses\u0020the\u0020given\u0020arguments\u0020for\u0020known\u0020options\u0020and\u0020command",
            "url": "classes/splitbrain-phpcli-Options.html#method_parseOptions"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\Options\u003A\u003AgetOpt\u0028\u0029",
            "name": "getOpt",
            "summary": "Get\u0020the\u0020value\u0020of\u0020the\u0020given\u0020option",
            "url": "classes/splitbrain-phpcli-Options.html#method_getOpt"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\Options\u003A\u003AgetCmd\u0028\u0029",
            "name": "getCmd",
            "summary": "Return\u0020the\u0020found\u0020command\u0020if\u0020any",
            "url": "classes/splitbrain-phpcli-Options.html#method_getCmd"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\Options\u003A\u003AgetArgs\u0028\u0029",
            "name": "getArgs",
            "summary": "Get\u0020all\u0020the\u0020arguments\u0020passed\u0020to\u0020the\u0020script",
            "url": "classes/splitbrain-phpcli-Options.html#method_getArgs"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\Options\u003A\u003Ahelp\u0028\u0029",
            "name": "help",
            "summary": "Builds\u0020a\u0020help\u0020screen\u0020from\u0020the\u0020available\u0020options.\u0020You\u0020may\u0020want\u0020to\u0020call\u0020it\u0020from\u0020\u002Dh\u0020or\u0020on\u0020error",
            "url": "classes/splitbrain-phpcli-Options.html#method_help"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\Options\u003A\u003AreadPHPArgv\u0028\u0029",
            "name": "readPHPArgv",
            "summary": "Safely\u0020read\u0020the\u0020\u0024argv\u0020PHP\u0020array\u0020across\u0020different\u0020PHP\u0020configurations.",
            "url": "classes/splitbrain-phpcli-Options.html#method_readPHPArgv"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\Options\u003A\u003A\u0024setup",
            "name": "setup",
            "summary": "",
            "url": "classes/splitbrain-phpcli-Options.html#property_setup"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\Options\u003A\u003A\u0024options",
            "name": "options",
            "summary": "",
            "url": "classes/splitbrain-phpcli-Options.html#property_options"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\Options\u003A\u003A\u0024command",
            "name": "command",
            "summary": "",
            "url": "classes/splitbrain-phpcli-Options.html#property_command"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\Options\u003A\u003A\u0024args",
            "name": "args",
            "summary": "",
            "url": "classes/splitbrain-phpcli-Options.html#property_args"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\Options\u003A\u003A\u0024bin",
            "name": "bin",
            "summary": "",
            "url": "classes/splitbrain-phpcli-Options.html#property_bin"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\Options\u003A\u003A\u0024colors",
            "name": "colors",
            "summary": "",
            "url": "classes/splitbrain-phpcli-Options.html#property_colors"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\Options\u003A\u003A\u0024newline",
            "name": "newline",
            "summary": "",
            "url": "classes/splitbrain-phpcli-Options.html#property_newline"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\PSR3CLI",
            "name": "PSR3CLI",
            "summary": "Class\u0020PSR3CLI",
            "url": "classes/splitbrain-phpcli-PSR3CLI.html"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\PSR3CLIv3",
            "name": "PSR3CLIv3",
            "summary": "Class\u0020PSR3CLI",
            "url": "classes/splitbrain-phpcli-PSR3CLIv3.html"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\PSR3CLIv3\u003A\u003Alog\u0028\u0029",
            "name": "log",
            "summary": "",
            "url": "classes/splitbrain-phpcli-PSR3CLIv3.html#method_log"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\TableFormatter",
            "name": "TableFormatter",
            "summary": "Class\u0020TableFormatter",
            "url": "classes/splitbrain-phpcli-TableFormatter.html"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\TableFormatter\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "TableFormatter\u0020constructor.",
            "url": "classes/splitbrain-phpcli-TableFormatter.html#method___construct"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\TableFormatter\u003A\u003AgetBorder\u0028\u0029",
            "name": "getBorder",
            "summary": "The\u0020currently\u0020set\u0020border\u0020\u0028defaults\u0020to\u0020\u0027\u0020\u0027\u0029",
            "url": "classes/splitbrain-phpcli-TableFormatter.html#method_getBorder"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\TableFormatter\u003A\u003AsetBorder\u0028\u0029",
            "name": "setBorder",
            "summary": "Set\u0020the\u0020border.\u0020The\u0020border\u0020is\u0020set\u0020between\u0020each\u0020column.\u0020Its\u0020width\u0020is\nadded\u0020to\u0020the\u0020column\u0020widths.",
            "url": "classes/splitbrain-phpcli-TableFormatter.html#method_setBorder"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\TableFormatter\u003A\u003AgetMaxWidth\u0028\u0029",
            "name": "getMaxWidth",
            "summary": "Width\u0020of\u0020the\u0020terminal\u0020in\u0020characters",
            "url": "classes/splitbrain-phpcli-TableFormatter.html#method_getMaxWidth"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\TableFormatter\u003A\u003AsetMaxWidth\u0028\u0029",
            "name": "setMaxWidth",
            "summary": "Set\u0020the\u0020width\u0020of\u0020the\u0020terminal\u0020to\u0020assume\u0020\u0028in\u0020characters\u0029",
            "url": "classes/splitbrain-phpcli-TableFormatter.html#method_setMaxWidth"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\TableFormatter\u003A\u003AgetTerminalWidth\u0028\u0029",
            "name": "getTerminalWidth",
            "summary": "Tries\u0020to\u0020figure\u0020out\u0020the\u0020width\u0020of\u0020the\u0020terminal",
            "url": "classes/splitbrain-phpcli-TableFormatter.html#method_getTerminalWidth"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\TableFormatter\u003A\u003AcalculateColLengths\u0028\u0029",
            "name": "calculateColLengths",
            "summary": "Takes\u0020an\u0020array\u0020with\u0020dynamic\u0020column\u0020width\u0020and\u0020calculates\u0020the\u0020correct\u0020width",
            "url": "classes/splitbrain-phpcli-TableFormatter.html#method_calculateColLengths"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\TableFormatter\u003A\u003Aformat\u0028\u0029",
            "name": "format",
            "summary": "Displays\u0020text\u0020in\u0020multiple\u0020word\u0020wrapped\u0020columns",
            "url": "classes/splitbrain-phpcli-TableFormatter.html#method_format"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\TableFormatter\u003A\u003Apad\u0028\u0029",
            "name": "pad",
            "summary": "Pad\u0020the\u0020given\u0020string\u0020to\u0020the\u0020correct\u0020length",
            "url": "classes/splitbrain-phpcli-TableFormatter.html#method_pad"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\TableFormatter\u003A\u003Astrlen\u0028\u0029",
            "name": "strlen",
            "summary": "Measures\u0020char\u0020length\u0020in\u0020UTF\u002D8\u0020when\u0020possible",
            "url": "classes/splitbrain-phpcli-TableFormatter.html#method_strlen"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\TableFormatter\u003A\u003Asubstr\u0028\u0029",
            "name": "substr",
            "summary": "",
            "url": "classes/splitbrain-phpcli-TableFormatter.html#method_substr"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\TableFormatter\u003A\u003Awordwrap\u0028\u0029",
            "name": "wordwrap",
            "summary": "",
            "url": "classes/splitbrain-phpcli-TableFormatter.html#method_wordwrap"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\TableFormatter\u003A\u003A\u0024border",
            "name": "border",
            "summary": "",
            "url": "classes/splitbrain-phpcli-TableFormatter.html#property_border"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\TableFormatter\u003A\u003A\u0024max",
            "name": "max",
            "summary": "",
            "url": "classes/splitbrain-phpcli-TableFormatter.html#property_max"
        },                {
            "fqsen": "\\splitbrain\\phpcli\\TableFormatter\u003A\u003A\u0024colors",
            "name": "colors",
            "summary": "",
            "url": "classes/splitbrain-phpcli-TableFormatter.html#property_colors"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\splitbrain\\phpcli",
            "name": "phpcli",
            "summary": "",
            "url": "namespaces/splitbrain-phpcli.html"
        },                {
            "fqsen": "\\splitbrain",
            "name": "splitbrain",
            "summary": "",
            "url": "namespaces/splitbrain.html"
        }            ]
);
